services:
  osudroid-profile-prod:
    container_name: osudroid_profile_prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - data-cache:/app/data
    networks:
      - caddy
    labels:
      caddy: odp.mysterken.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped

volumes:
  data-cache:

networks:
  caddy:
    external: true
