services:
  osudroid-profile-prod:
    container_name: osudroid_profile_prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - data-cache:/app/data
    restart: unless-stopped

volumes:
  data-cache:
